import type { Metadata } from "next";
import { Inter, Manrope } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import AppProvider from "@/components/provider/AppProvider";
import { PaymentSheet } from "@/components/pricing/PaymentSheet";
const sans = Manrope({
  variable: "--font-sans",
  subsets: ["latin"],
});

const serif = Inter({
  variable: "--font-serif",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sans.variable} ${serif.variable} font-sans antialiased`}
      >
        <AppProvider>
          {children}
          <div className="fixed inset-0 -z-10 h-full w-full  bg-[linear-gradient(to_right,#8080800a_1px,transparent_1px),linear-gradient(to_bottom,#8080800a_1px,transparent_1px)] bg-[size:14px_24px]"></div>
          <Toaster />

          <PaymentSheet />
        </AppProvider>
      </body>
    </html>
  );
}
